CREATE TABLE IF NOT EXISTS registrations (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	tenant_id UUID NOT NULL,
	client_id UUID NOT NULL,
	registration_type VARCHAR(100) NOT NULL,
	company_name VARCHAR(255) NOT NULL,
	registration_number VARCHAR(100),
	jurisdiction VARCHAR(2) NOT NULL,
	status VARCHAR(50) NOT NULL DEFAULT 'draft',
	submitted_at TIMESTAMP,
	approved_at TIMESTAMP,
	rejected_at TIMESTAMP,
	rejection_reason TEXT,
	assigned_to VARCHAR(255),
	cipc_reference VARCHAR(255),
	dcip_reference VARCHAR(255),
	odoo_lead_id INTEGER,
	odoo_project_id INTEGER,
	odoo_invoice_id INTEGER,
	form_data JSONB DEFAULT '{}'::jsonb,
	metadata JSONB DEFAULT '{}'::jsonb,
	created_at TIMESTAMP NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
	deleted_at TIMESTAMP
)
